apiVersion: v1
kind: Pod
metadata:
  name: user-service
  labels:
    tier: back-end
spec:
  containers:
    - name: user-service
      image: darshana991/user-service:latest
      ports:
        - containerPort: 9090
      imagePullPolicy: Always